---
- name: "validate app_user"
  assert:
    that:
      - "app_user is defined"
      - "app_user|length <= 32"
    msg: "'app_user' must be defined and <= 32 characters"

- name: "set app_group to app_user"
  set_fact:
    app_group: "{{ app_user[:16] }}"
  when: "app_group is not defined"

- name: "validate app_group"
  assert:
    that:
      - "app_group is defined"
      - "app_group|length <= 16"
    msg: "'app_group' must be defined and <= 16 characters"

- block:
  - name: "set app_admin_group"
    set_fact:
      app_admin_group: "{{ app_group[:10] }}_admin"
    when: "app_admin_group is not defined"

  - name: "validate app_admin_group"
    assert:
      that:
        - "app_admin_group is defined"
        - "app_admin_group|length <= 16"
      msg: "'app_admin_group' must be defined and <= 16 characters"

  - name: "set app_admin_users"
    set_fact:
     app_admin_users:
        - "{{ ansible_user_id }}"
    when: "app_admin_users is not defined"

  - name: "validate app_admin_users is a list"
    assert:
      that:
        - "app_admin_users is defined"
        - "app_admin_users is iterable and app_admin_users is not string"

  - name: "ensure that sudo is properly configured before changes"
    command: '/usr/sbin/visudo -c'
    become: true
  when: "app_admin_sudo|default(false)"

- block:
  - name: "create application group"
    group:
      name: "{{ app_group }}"
      state: present

  - name: "create application user"
    user:
      name: "{{ app_user }}"
      group: "{{ app_group }}"
  become: true
- debug: var=app_admin_group
- debug: var=app_admin_users
- debug: var=ansible_user_id
